<?php
    $config = [
        "name" => "web",
        "description" => "Plugin para gestionar web",
        "version" => "1",
        "precio" => "10",
        "menuadmin" => [
            [
                "menuadmin_parent" => "",
                "menuadmin_menuadmin_id" => 0,
                "menuadmin_type" => 2,
                "menuadmin_name" => "Web",
                "menuadmin_url" => "",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_posicion" => "97",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Web",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Ver web",
                "menuadmin_url" => "",
                "menuadmin_icon" => "web",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Web",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Banners",
                "menuadmin_url" => "admin/banners",
                "menuadmin_icon" => "view_carousel",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Web",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Páginas",
                "menuadmin_url" => "admin/paginas",
                "menuadmin_icon" => "library_books",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Web",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Menu",
                "menuadmin_url" => "admin/menus",
                "menuadmin_icon" => "apps",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Web",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Grupo Menu",
                "menuadmin_url" => "admin/grupomenus",
                "menuadmin_icon" => "art_track",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Web",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Galería",
                "menuadmin_url" => "",
                "menuadmin_icon" => "perm_media",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Galería",
                "menuadmin_type" => 1,
                "menuadmin_name" => "Imagenes",
                "menuadmin_url" => "admin/galeria/imagenes",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Galería",
                "menuadmin_type" => 1,
                "menuadmin_name" => "Documentos",
                "menuadmin_url" => "admin/galeria/documentos",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [
                "menuadmin_parent" => "Galería",
                "menuadmin_type" => 1,
                "menuadmin_name" => "Videos",
                "menuadmin_url" => "admin/galeria/videos",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ],
        ],
        "updates" => [
            [
                "from" => "Updates/Config/Routes.php",
                "to" => "Config/Routes.php",
                "Type" => "update",
            ],
        ],
    ];
?>
