<?php
    $config = [
        "name" => "core",
        "description" => "Base de StarOnline",
        "version" => "1",
        "precio" => "0",
        "menuadmin" => [
            [ //1
                "menuadmin_parent" => "",
                "menuadmin_type" => 2,
                "menuadmin_name" => "Avanzado",
                "menuadmin_url" => "",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_posicion" => "99",
                "menuadmin_estado" => 1,
            ], [ //2
                "menuadmin_parent" => "Avanzado",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Plugins",
                "menuadmin_url" => "admin/plugins",
                "menuadmin_icon" => "dashboard",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ],[ //3
                "menuadmin_parent" => "Avanzado",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Gestion de usuarios",
                "menuadmin_url" => "",
                "menuadmin_icon" => "people",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [ //4
                "menuadmin_parent" => "Gestion de usuarios",
                "menuadmin_type" => 1,
                "menuadmin_name" => "Usuarios",
                "menuadmin_url" => "admin/usuarios",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [// 5
                "menuadmin_parent" => "Gestion de usuarios",
                "menuadmin_type" => 1,
                "menuadmin_name" => "Roles",
                "menuadmin_url" => "admin/roles",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [// 6
                "menuadmin_parent" => "Gestion de usuarios",
                "menuadmin_type" => 1,
                "menuadmin_name" => "Permisos",
                "menuadmin_url" => "admin/permisos",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [// 7
                "menuadmin_parent" => "Avanzado",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Configuracion",
                "menuadmin_url" => "",
                "menuadmin_icon" => "build",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [ //8
                "menuadmin_parent" => "Configuracion",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Configuración general",
                "menuadmin_url" => "admin/configuracion",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [ //9
                "menuadmin_parent" => "Configuracion",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Seleccionar tema",
                "menuadmin_url" => "admin/configuracion/temas",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ],[ //10
                "menuadmin_parent" => "Avanzado",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Configuracion tienda",
                "menuadmin_url" => "",
                "menuadmin_icon" => "build",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ], [ //11
                "menuadmin_parent" => "Configuracion",
                "menuadmin_type" => 0,
                "menuadmin_name" => "Configuración Menu Admin",
                "menuadmin_url" => "admin/menusadmin",
                "menuadmin_icon" => "",
                "menuadmin_custom" => "",
                "menuadmin_estado" => 1,
            ],
        ],
        "updates" => [
            [
                "from" => "Updates/Config/Routes.php",
                "to" => "Config/Routes.php",
                "Type" => "update",
            ],
        ],
    ];
?>
