<?php namespace App\Database\Seeds;

class PaisSeeder extends \CodeIgniter\Database\Seeder{
        public function run(){
            $db = \Config\Database::connect();
            $paises = [
                ["nombre" => "Afganistán", "alpha2" => "AF", "alpha3" => "AFG", "codigo" => "4"],
                ["nombre" => "Åland, Islas", "alpha2" => "AX", "alpha3" => "ALA", "codigo" => "248"],
                ["nombre" => "Albania", "alpha2" => "AL", "alpha3" => "ALB", "codigo" => "8"],
                ["nombre" => "Alemania", "alpha2" => "DE", "alpha3" => "DEU", "codigo" => "276"],
                ["nombre" => "Andorra", "alpha2" => "AD", "alpha3" => "AND", "codigo" => "20"],
                ["nombre" => "Angola", "alpha2" => "AO", "alpha3" => "AGO", "codigo" => "24"],
                ["nombre" => "Anguila", "alpha2" => "AI", "alpha3" => "AIA", "codigo" => "660"],
                ["nombre" => "Antártida", "alpha2" => "AQ", "alpha3" => "ATA", "codigo" => "10"],
                ["nombre" => "Antigua y Barbuda", "alpha2" => "AG", "alpha3" => "ATG", "codigo" => "28"],
                ["nombre" => "Arabia Saudita", "alpha2" => "SA", "alpha3" => "SAU", "codigo" => "682"],
                ["nombre" => "Argelia", "alpha2" => "DZ", "alpha3" => "DZA", "codigo" => "12"],
                ["nombre" => "Argentina", "alpha2" => "AR", "alpha3" => "ARG", "codigo" => "32"],
                ["nombre" => "Armenia", "alpha2" => "AM", "alpha3" => "ARM", "codigo" => "51"],
                ["nombre" => "Aruba", "alpha2" => "AW", "alpha3" => "ABW", "codigo" => "533"],
                ["nombre" => "Australia", "alpha2" => "AU", "alpha3" => "AUS", "codigo" => "36"],
                ["nombre" => "Austria", "alpha2" => "AT", "alpha3" => "AUT", "codigo" => "40"],
                ["nombre" => "Azerbaiyán", "alpha2" => "AZ", "alpha3" => "AZE", "codigo" => "31"],
                ["nombre" => "Bahamas (las)", "alpha2" => "BS", "alpha3" => "BHS", "codigo" => "44"],
                ["nombre" => "Bangladesh", "alpha2" => "BD", "alpha3" => "BGD", "codigo" => "50"],
                ["nombre" => "Barbados", "alpha2" => "BB", "alpha3" => "BRB", "codigo" => "52"],
                ["nombre" => "Bahrein", "alpha2" => "BH", "alpha3" => "BHR", "codigo" => "48"],
                ["nombre" => "Bélgica", "alpha2" => "BE", "alpha3" => "BEL", "codigo" => "56"],
                ["nombre" => "Belice", "alpha2" => "BZ", "alpha3" => "BLZ", "codigo" => "84"],
                ["nombre" => "Benín", "alpha2" => "BJ", "alpha3" => "BEN", "codigo" => "204"],
                ["nombre" => "Bermudas", "alpha2" => "BM", "alpha3" => "BMU", "codigo" => "60"],
                ["nombre" => "Belarús", "alpha2" => "BY", "alpha3" => "BLR", "codigo" => "112"],
                ["nombre" => "Bolivia (Estado Plurinacional de)", "alpha2" => "BO", "alpha3" => "BOL", "codigo" => "68"],
                ["nombre" => "Bonaire, San Eustaquio y Saba", "alpha2" => "BQ", "alpha3" => "BES", "codigo" => "535"],
                ["nombre" => "Bosnia y Herzegovina", "alpha2" => "BA", "alpha3" => "BIH", "codigo" => "70"],
                ["nombre" => "Botswana", "alpha2" => "BW", "alpha3" => "BWA", "codigo" => "72"],
                ["nombre" => "Brasil", "alpha2" => "BR", "alpha3" => "BRA", "codigo" => "76"],
                ["nombre" => "Brunei Darussalam", "alpha2" => "BN", "alpha3" => "BRN", "codigo" => "96"],
                ["nombre" => "Bulgaria", "alpha2" => "BG", "alpha3" => "BGR", "codigo" => "100"],
                ["nombre" => "Burkina Faso", "alpha2" => "BF", "alpha3" => "BFA", "codigo" => "854"],
                ["nombre" => "Burundi", "alpha2" => "BI", "alpha3" => "BDI", "codigo" => "108"],
                ["nombre" => "Bhután", "alpha2" => "BT", "alpha3" => "BTN", "codigo" => "64"],
                ["nombre" => "Cabo Verde", "alpha2" => "CV", "alpha3" => "CPV", "codigo" => "132"],
                ["nombre" => "Camboya", "alpha2" => "KH", "alpha3" => "KHM", "codigo" => "116"],
                ["nombre" => "Camerún", "alpha2" => "CM", "alpha3" => "CMR", "codigo" => "120"],
                ["nombre" => "Canadá", "alpha2" => "CA", "alpha3" => "CAN", "codigo" => "124"],
                ["nombre" => "Qatar", "alpha2" => "QA", "alpha3" => "QAT", "codigo" => "634"],
                ["nombre" => "Chad", "alpha2" => "TD", "alpha3" => "TCD", "codigo" => "148"],
                ["nombre" => "Chile", "alpha2" => "CL", "alpha3" => "CHL", "codigo" => "152"],
                ["nombre" => "China", "alpha2" => "CN", "alpha3" => "CHN", "codigo" => "156"],
                ["nombre" => "Chipre", "alpha2" => "CY", "alpha3" => "CYP", "codigo" => "196"],
                ["nombre" => "Colombia", "alpha2" => "CO", "alpha3" => "COL", "codigo" => "170"],
                ["nombre" => "Comoras (las)", "alpha2" => "KM", "alpha3" => "COM", "codigo" => "174"],
                ["nombre" => "Corea (la República Popular Democrática de)", "alpha2" => "KP", "alpha3" => "PRK", "codigo" => "408"],
                ["nombre" => "Corea (la República de)", "alpha2" => "KR", "alpha3" => "KOR", "codigo" => "410"],
                ["nombre" => "Côte d'Ivoire", "alpha2" => "CI", "alpha3" => "CIV", "codigo" => "384"],
                ["nombre" => "Costa Rica", "alpha2" => "CR", "alpha3" => "CRI", "codigo" => "188"],
                ["nombre" => "Croacia", "alpha2" => "HR", "alpha3" => "HRV", "codigo" => "191"],
                ["nombre" => "Cuba", "alpha2" => "CU", "alpha3" => "CUB", "codigo" => "192"],
                ["nombre" => "Curaçao", "alpha2" => "CW", "alpha3" => "CUW", "codigo" => "531"],
                ["nombre" => "Dinamarca", "alpha2" => "DK", "alpha3" => "DNK", "codigo" => "208"],
                ["nombre" => "Dominica", "alpha2" => "DM", "alpha3" => "DMA", "codigo" => "212"],
                ["nombre" => "Ecuador", "alpha2" => "EC", "alpha3" => "ECU", "codigo" => "218"],
                ["nombre" => "Egipto", "alpha2" => "EG", "alpha3" => "EGY", "codigo" => "818"],
                ["nombre" => "El Salvador", "alpha2" => "SV", "alpha3" => "SLV", "codigo" => "222"],
                ["nombre" => "Emiratos Árabes Unidos (los)", "alpha2" => "AE", "alpha3" => "ARE", "codigo" => "784"],
                ["nombre" => "Eritrea", "alpha2" => "ER", "alpha3" => "ERI", "codigo" => "232"],
                ["nombre" => "Eslovaquia", "alpha2" => "SK", "alpha3" => "SVK", "codigo" => "703"],
                ["nombre" => "Eslovenia", "alpha2" => "SI", "alpha3" => "SVN", "codigo" => "705"],
                ["nombre" => "España", "alpha2" => "ES", "alpha3" => "ESP", "codigo" => "724"],
                ["nombre" => "Estados Unidos de América (los)", "alpha2" => "US", "alpha3" => "USA", "codigo" => "840"],
                ["nombre" => "Estonia", "alpha2" => "EE", "alpha3" => "EST", "codigo" => "233"],
                ["nombre" => "Etiopía", "alpha2" => "ET", "alpha3" => "ETH", "codigo" => "231"],
                ["nombre" => "Filipinas (las)", "alpha2" => "PH", "alpha3" => "PHL", "codigo" => "608"],
                ["nombre" => "Finlandia", "alpha2" => "FI", "alpha3" => "FIN", "codigo" => "246"],
                ["nombre" => "Fiji", "alpha2" => "FJ", "alpha3" => "FJI", "codigo" => "242"],
                ["nombre" => "Francia", "alpha2" => "FR", "alpha3" => "FRA", "codigo" => "250"],
                ["nombre" => "Gabón", "alpha2" => "GA", "alpha3" => "GAB", "codigo" => "266"],
                ["nombre" => "Gambia (la)", "alpha2" => "GM", "alpha3" => "GMB", "codigo" => "270"],
                ["nombre" => "Georgia", "alpha2" => "GE", "alpha3" => "GEO", "codigo" => "268"],
                ["nombre" => "Ghana", "alpha2" => "GH", "alpha3" => "GHA", "codigo" => "288"],
                ["nombre" => "Gibraltar", "alpha2" => "GI", "alpha3" => "GIB", "codigo" => "292"],
                ["nombre" => "Granada", "alpha2" => "GD", "alpha3" => "GRD", "codigo" => "308"],
                ["nombre" => "Grecia", "alpha2" => "GR", "alpha3" => "GRC", "codigo" => "300"],
                ["nombre" => "Groenlandia", "alpha2" => "GL", "alpha3" => "GRL", "codigo" => "304"],
                ["nombre" => "Guadeloupe", "alpha2" => "GP", "alpha3" => "GLP", "codigo" => "312"],
                ["nombre" => "Guam", "alpha2" => "GU", "alpha3" => "GUM", "codigo" => "316"],
                ["nombre" => "Guatemala", "alpha2" => "GT", "alpha3" => "GTM", "codigo" => "320"],
                ["nombre" => "Guayana Francesa", "alpha2" => "GF", "alpha3" => "GUF", "codigo" => "254"],
                ["nombre" => "Guernsey", "alpha2" => "GG", "alpha3" => "GGY", "codigo" => "831"],
                ["nombre" => "Guinea", "alpha2" => "GN", "alpha3" => "GIN", "codigo" => "324"],
                ["nombre" => "Guinea Bissau", "alpha2" => "GW", "alpha3" => "GNB", "codigo" => "624"],
                ["nombre" => "Guinea Ecuatorial", "alpha2" => "GQ", "alpha3" => "GNQ", "codigo" => "226"],
                ["nombre" => "Guyana", "alpha2" => "GY", "alpha3" => "GUY", "codigo" => "328"],
                ["nombre" => "Haití", "alpha2" => "HT", "alpha3" => "HTI", "codigo" => "332"],
                ["nombre" => "Honduras", "alpha2" => "HN", "alpha3" => "HND", "codigo" => "340"],
                ["nombre" => "Hong Kong", "alpha2" => "HK", "alpha3" => "HKG", "codigo" => "344"],
                ["nombre" => "Hungría", "alpha2" => "HU", "alpha3" => "HUN", "codigo" => "348"],
                ["nombre" => "India", "alpha2" => "IN", "alpha3" => "IND", "codigo" => "356"],
                ["nombre" => "Indonesia", "alpha2" => "ID", "alpha3" => "IDN", "codigo" => "360"],
                ["nombre" => "Iraq", "alpha2" => "IQ", "alpha3" => "IRQ", "codigo" => "368"],
                ["nombre" => "Irán (República Islámica de)", "alpha2" => "IR", "alpha3" => "IRN", "codigo" => "364"],
                ["nombre" => "Irlanda", "alpha2" => "IE", "alpha3" => "IRL", "codigo" => "372"],
                ["nombre" => "Bouvet, Isla", "alpha2" => "BV", "alpha3" => "BVT", "codigo" => "74"],
                ["nombre" => "Isla de Man", "alpha2" => "IM", "alpha3" => "IMN", "codigo" => "833"],
                ["nombre" => "Navidad, Isla de", "alpha2" => "CX", "alpha3" => "CXR", "codigo" => "162"],
                ["nombre" => "Islandia", "alpha2" => "IS", "alpha3" => "ISL", "codigo" => "352"],
                ["nombre" => "Caimán, (las) Islas", "alpha2" => "KY", "alpha3" => "CYM", "codigo" => "136"],
                ["nombre" => "Cocos / Keeling, (las) Islas", "alpha2" => "CC", "alpha3" => "CCK", "codigo" => "166"],
                ["nombre" => "Cook, (las) Islas", "alpha2" => "CK", "alpha3" => "COK", "codigo" => "184"],
                ["nombre" => "Feroe, (las) Islas", "alpha2" => "FO", "alpha3" => "FRO", "codigo" => "234"],
                ["nombre" => "Georgia del Sur (la) y las Islas Sandwich del Sur", "alpha2" => "GS", "alpha3" => "SGS", "codigo" => "239"],
                ["nombre" => "Heard (Isla) e Islas McDonald", "alpha2" => "HM", "alpha3" => "HMD", "codigo" => "334"],
                ["nombre" => "Malvinas [Falkland], (las) Islas", "alpha2" => "FK", "alpha3" => "FLK", "codigo" => "238"],
                ["nombre" => "Marianas del Norte, (las) Islas", "alpha2" => "MP", "alpha3" => "MNP", "codigo" => "580"],
                ["nombre" => "Marshall, (las) Islas", "alpha2" => "MH", "alpha3" => "MHL", "codigo" => "584"],
                ["nombre" => "Pitcairn", "alpha2" => "PN", "alpha3" => "PCN", "codigo" => "612"],
                ["nombre" => "Salomón, Islas", "alpha2" => "SB", "alpha3" => "SLB", "codigo" => "90"],
                ["nombre" => "Turcas y Caicos, (las) Islas", "alpha2" => "TC", "alpha3" => "TCA", "codigo" => "796"],
                ["nombre" => "Islas Ultramarinas Menores de los Estados Unidos (las)", "alpha2" => "UM", "alpha3" => "UMI", "codigo" => "581"],
                ["nombre" => "Vírgenes británicas, Islas", "alpha2" => "VG", "alpha3" => "VGB", "codigo" => "92"],
                ["nombre" => "Vírgenes de los Estados Unidos, Islas", "alpha2" => "VI", "alpha3" => "VIR", "codigo" => "850"],
                ["nombre" => "Israel", "alpha2" => "IL", "alpha3" => "ISR", "codigo" => "376"],
                ["nombre" => "Italia", "alpha2" => "IT", "alpha3" => "ITA", "codigo" => "380"],
                ["nombre" => "Jamaica", "alpha2" => "JM", "alpha3" => "JAM", "codigo" => "388"],
                ["nombre" => "Japón", "alpha2" => "JP", "alpha3" => "JPN", "codigo" => "392"],
                ["nombre" => "Jersey", "alpha2" => "JE", "alpha3" => "JEY", "codigo" => "832"],
                ["nombre" => "Jordania", "alpha2" => "JO", "alpha3" => "JOR", "codigo" => "400"],
                ["nombre" => "Kazajstán", "alpha2" => "KZ", "alpha3" => "KAZ", "codigo" => "398"],
                ["nombre" => "Kenya", "alpha2" => "KE", "alpha3" => "KEN", "codigo" => "404"],
                ["nombre" => "Kirguistán", "alpha2" => "KG", "alpha3" => "KGZ", "codigo" => "417"],
                ["nombre" => "Kiribati", "alpha2" => "KI", "alpha3" => "KIR", "codigo" => "296"],
                ["nombre" => "Kuwait", "alpha2" => "KW", "alpha3" => "KWT", "codigo" => "414"],
                ["nombre" => "Lao, (la) República Democrática Popular", "alpha2" => "LA", "alpha3" => "LAO", "codigo" => "418"],
                ["nombre" => "Lesotho", "alpha2" => "LS", "alpha3" => "LSO", "codigo" => "426"],
                ["nombre" => "Letonia", "alpha2" => "LV", "alpha3" => "LVA", "codigo" => "428"],
                ["nombre" => "Líbano", "alpha2" => "LB", "alpha3" => "LBN", "codigo" => "422"],
                ["nombre" => "Liberia", "alpha2" => "LR", "alpha3" => "LBR", "codigo" => "430"],
                ["nombre" => "Libia", "alpha2" => "LY", "alpha3" => "LBY", "codigo" => "434"],
                ["nombre" => "Liechtenstein", "alpha2" => "LI", "alpha3" => "LIE", "codigo" => "438"],
                ["nombre" => "Lituania", "alpha2" => "LT", "alpha3" => "LTU", "codigo" => "440"],
                ["nombre" => "Luxemburgo", "alpha2" => "LU", "alpha3" => "LUX", "codigo" => "442"],
                ["nombre" => "Macao", "alpha2" => "MO", "alpha3" => "MAC", "codigo" => "446"],
                ["nombre" => "Macedonia del Norte", "alpha2" => "MK", "alpha3" => "MKD", "codigo" => "807"],
                ["nombre" => "Madagascar", "alpha2" => "MG", "alpha3" => "MDG", "codigo" => "450"],
                ["nombre" => "Malasia", "alpha2" => "MY", "alpha3" => "MYS", "codigo" => "458"],
                ["nombre" => "Malawi", "alpha2" => "MW", "alpha3" => "MWI", "codigo" => "454"],
                ["nombre" => "Maldivas", "alpha2" => "MV", "alpha3" => "MDV", "codigo" => "462"],
                ["nombre" => "Malí", "alpha2" => "ML", "alpha3" => "MLI", "codigo" => "466"],
                ["nombre" => "Malta", "alpha2" => "MT", "alpha3" => "MLT", "codigo" => "470"],
                ["nombre" => "Marruecos", "alpha2" => "MA", "alpha3" => "MAR", "codigo" => "504"],
                ["nombre" => "Martinique", "alpha2" => "MQ", "alpha3" => "MTQ", "codigo" => "474"],
                ["nombre" => "Mauricio", "alpha2" => "MU", "alpha3" => "MUS", "codigo" => "480"],
                ["nombre" => "Mauritania", "alpha2" => "MR", "alpha3" => "MRT", "codigo" => "478"],
                ["nombre" => "Mayotte", "alpha2" => "YT", "alpha3" => "MYT", "codigo" => "175"],
                ["nombre" => "México", "alpha2" => "MX", "alpha3" => "MEX", "codigo" => "484"],
                ["nombre" => "Micronesia (Estados Federados de)", "alpha2" => "FM", "alpha3" => "FSM", "codigo" => "583"],
                ["nombre" => "Moldova (la República de)", "alpha2" => "MD", "alpha3" => "MDA", "codigo" => "498"],
                ["nombre" => "Mónaco", "alpha2" => "MC", "alpha3" => "MCO", "codigo" => "492"],
                ["nombre" => "Mongolia", "alpha2" => "MN", "alpha3" => "MNG", "codigo" => "496"],
                ["nombre" => "Montenegro", "alpha2" => "ME", "alpha3" => "MNE", "codigo" => "499"],
                ["nombre" => "Montserrat", "alpha2" => "MS", "alpha3" => "MSR", "codigo" => "500"],
                ["nombre" => "Mozambique", "alpha2" => "MZ", "alpha3" => "MOZ", "codigo" => "508"],
                ["nombre" => "Myanmar", "alpha2" => "MM", "alpha3" => "MMR", "codigo" => "104"],
                ["nombre" => "Namibia", "alpha2" => "NA", "alpha3" => "NAM", "codigo" => "516"],
                ["nombre" => "Nauru", "alpha2" => "NR", "alpha3" => "NRU", "codigo" => "520"],
                ["nombre" => "Nepal", "alpha2" => "NP", "alpha3" => "NPL", "codigo" => "524"],
                ["nombre" => "Nicaragua", "alpha2" => "NI", "alpha3" => "NIC", "codigo" => "558"],
                ["nombre" => "Níger (el)", "alpha2" => "NE", "alpha3" => "NER", "codigo" => "562"],
                ["nombre" => "Nigeria", "alpha2" => "NG", "alpha3" => "NGA", "codigo" => "566"],
                ["nombre" => "Niue", "alpha2" => "NU", "alpha3" => "NIU", "codigo" => "570"],
                ["nombre" => "Norfolk, Isla", "alpha2" => "NF", "alpha3" => "NFK", "codigo" => "574"],
                ["nombre" => "Noruega", "alpha2" => "NO", "alpha3" => "NOR", "codigo" => "578"],
                ["nombre" => "Nueva Caledonia", "alpha2" => "NC", "alpha3" => "NCL", "codigo" => "540"],
                ["nombre" => "Nueva Zelandia", "alpha2" => "NZ", "alpha3" => "NZL", "codigo" => "554"],
                ["nombre" => "Omán", "alpha2" => "OM", "alpha3" => "OMN", "codigo" => "512"],
                ["nombre" => "Países Bajos (los)", "alpha2" => "NL", "alpha3" => "NLD", "codigo" => "528"],
                ["nombre" => "Pakistán", "alpha2" => "PK", "alpha3" => "PAK", "codigo" => "586"],
                ["nombre" => "Palau", "alpha2" => "PW", "alpha3" => "PLW", "codigo" => "585"],
                ["nombre" => "Palestina, Estado de", "alpha2" => "PS", "alpha3" => "PSE", "codigo" => "275"],
                ["nombre" => "Panamá", "alpha2" => "PA", "alpha3" => "PAN", "codigo" => "591"],
                ["nombre" => "Papua Nueva Guinea", "alpha2" => "PG", "alpha3" => "PNG", "codigo" => "598"],
                ["nombre" => "Paraguay", "alpha2" => "PY", "alpha3" => "PRY", "codigo" => "600"],
                ["nombre" => "Perú", "alpha2" => "PE", "alpha3" => "PER", "codigo" => "604"],
                ["nombre" => "Polinesia Francesa", "alpha2" => "PF", "alpha3" => "PYF", "codigo" => "258"],
                ["nombre" => "Polonia", "alpha2" => "PL", "alpha3" => "POL", "codigo" => "616"],
                ["nombre" => "Portugal", "alpha2" => "PT", "alpha3" => "PRT", "codigo" => "620"],
                ["nombre" => "Puerto Rico", "alpha2" => "PR", "alpha3" => "PRI", "codigo" => "630"],
                ["nombre" => "Reino Unido de Gran Bretaña e Irlanda del Norte (el)", "alpha2" => "GB", "alpha3" => "GBR", "codigo" => "826"],
                ["nombre" => "Sahara Occidental", "alpha2" => "EH", "alpha3" => "ESH", "codigo" => "732"],
                ["nombre" => "República Centroafricana (la)", "alpha2" => "CF", "alpha3" => "CAF", "codigo" => "140"],
                ["nombre" => "Chequia", "alpha2" => "CZ", "alpha3" => "CZE", "codigo" => "203"],
                ["nombre" => "Congo (el)", "alpha2" => "CG", "alpha3" => "COG", "codigo" => "178"],
                ["nombre" => "Congo (la República Democrática del)", "alpha2" => "CD", "alpha3" => "COD", "codigo" => "180"],
                ["nombre" => "Dominicana, (la) República", "alpha2" => "DO", "alpha3" => "DOM", "codigo" => "214"],
                ["nombre" => "Reunión", "alpha2" => "RE", "alpha3" => "REU", "codigo" => "638"],
                ["nombre" => "Rwanda", "alpha2" => "RW", "alpha3" => "RWA", "codigo" => "646"],
                ["nombre" => "Rumania", "alpha2" => "RO", "alpha3" => "ROU", "codigo" => "642"],
                ["nombre" => "Rusia, (la) Federación de", "alpha2" => "RU", "alpha3" => "RUS", "codigo" => "643"],
                ["nombre" => "Samoa", "alpha2" => "WS", "alpha3" => "WSM", "codigo" => "882"],
                ["nombre" => "Samoa Americana", "alpha2" => "AS", "alpha3" => "ASM", "codigo" => "16"],
                ["nombre" => "Saint Barthélemy", "alpha2" => "BL", "alpha3" => "BLM", "codigo" => "652"],
                ["nombre" => "Saint Kitts y Nevis", "alpha2" => "KN", "alpha3" => "KNA", "codigo" => "659"],
                ["nombre" => "San Marino", "alpha2" => "SM", "alpha3" => "SMR", "codigo" => "674"],
                ["nombre" => "Saint Martin (parte francesa)", "alpha2" => "MF", "alpha3" => "MAF", "codigo" => "663"],
                ["nombre" => "San Pedro y Miquelón", "alpha2" => "PM", "alpha3" => "SPM", "codigo" => "666"],
                ["nombre" => "San Vicente y las Granadinas", "alpha2" => "VC", "alpha3" => "VCT", "codigo" => "670"],
                ["nombre" => "Santa Helena, Ascensión y Tristán de Acuña", "alpha2" => "SH", "alpha3" => "SHN", "codigo" => "654"],
                ["nombre" => "Santa Lucía", "alpha2" => "LC", "alpha3" => "LCA", "codigo" => "662"],
                ["nombre" => "Santo Tomé y Príncipe", "alpha2" => "ST", "alpha3" => "STP", "codigo" => "678"],
                ["nombre" => "Senegal", "alpha2" => "SN", "alpha3" => "SEN", "codigo" => "686"],
                ["nombre" => "Serbia", "alpha2" => "RS", "alpha3" => "SRB", "codigo" => "688"],
                ["nombre" => "Seychelles", "alpha2" => "SC", "alpha3" => "SYC", "codigo" => "690"],
                ["nombre" => "Sierra leona", "alpha2" => "SL", "alpha3" => "SLE", "codigo" => "694"],
                ["nombre" => "Singapur", "alpha2" => "SG", "alpha3" => "SGP", "codigo" => "702"],
                ["nombre" => "Sint Maarten (parte neerlandesa)", "alpha2" => "SX", "alpha3" => "SXM", "codigo" => "534"],
                ["nombre" => "República Árabe Siria", "alpha2" => "SY", "alpha3" => "SYR", "codigo" => "760"],
                ["nombre" => "Somalia", "alpha2" => "SO", "alpha3" => "SOM", "codigo" => "706"],
                ["nombre" => "Sri Lanka", "alpha2" => "LK", "alpha3" => "LKA", "codigo" => "144"],
                ["nombre" => "Suazilandia", "alpha2" => "SZ", "alpha3" => "SWZ", "codigo" => "748"],
                ["nombre" => "Sudáfrica", "alpha2" => "ZA", "alpha3" => "ZAF", "codigo" => "710"],
                ["nombre" => "Sudán (el)", "alpha2" => "SD", "alpha3" => "SDN", "codigo" => "729"],
                ["nombre" => "Sudán del Sur", "alpha2" => "SS", "alpha3" => "SSD", "codigo" => "728"],
                ["nombre" => "Suecia", "alpha2" => "SE", "alpha3" => "SWE", "codigo" => "752"],
                ["nombre" => "Suiza", "alpha2" => "CH", "alpha3" => "CHE", "codigo" => "756"],
                ["nombre" => "Suriname", "alpha2" => "SR", "alpha3" => "SUR", "codigo" => "740"],
                ["nombre" => "Svalbard y Jan Mayen", "alpha2" => "SJ", "alpha3" => "SJM", "codigo" => "744"],
                ["nombre" => "Tailandia", "alpha2" => "TH", "alpha3" => "THA", "codigo" => "764"],
                ["nombre" => "Taiwán (Provincia de China)", "alpha2" => "TW", "alpha3" => "TWN", "codigo" => "158"],
                ["nombre" => "Tanzania, República Unida de", "alpha2" => "TZ", "alpha3" => "TZA", "codigo" => "834"],
                ["nombre" => "Tayikistán", "alpha2" => "TJ", "alpha3" => "TJK", "codigo" => "762"],
                ["nombre" => "Territorio Británico del Océano Índico (el)", "alpha2" => "IO", "alpha3" => "IOT", "codigo" => "86"],
                ["nombre" => "Tierras Australes Francesas (las)", "alpha2" => "TF", "alpha3" => "ATF", "codigo" => "260"],
                ["nombre" => "Timor-Leste", "alpha2" => "TL", "alpha3" => "TLS", "codigo" => "626"],
                ["nombre" => "Togo", "alpha2" => "TG", "alpha3" => "TGO", "codigo" => "768"],
                ["nombre" => "Tokelau", "alpha2" => "TK", "alpha3" => "TKL", "codigo" => "772"],
                ["nombre" => "Tonga", "alpha2" => "TO", "alpha3" => "TON", "codigo" => "776"],
                ["nombre" => "Trinidad y Tobago", "alpha2" => "TT", "alpha3" => "TTO", "codigo" => "780"],
                ["nombre" => "Túnez", "alpha2" => "TN", "alpha3" => "TUN", "codigo" => "788"],
                ["nombre" => "Turkmenistán", "alpha2" => "TM", "alpha3" => "TKM", "codigo" => "795"],
                ["nombre" => "Turquía", "alpha2" => "TR", "alpha3" => "TUR", "codigo" => "792"],
                ["nombre" => "Tuvalu", "alpha2" => "TV", "alpha3" => "TUV", "codigo" => "798"],
                ["nombre" => "Ucrania", "alpha2" => "UA", "alpha3" => "UKR", "codigo" => "804"],
                ["nombre" => "Uganda", "alpha2" => "UG", "alpha3" => "UGA", "codigo" => "800"],
                ["nombre" => "Uruguay", "alpha2" => "UY", "alpha3" => "URY", "codigo" => "858"],
                ["nombre" => "Uzbekistán", "alpha2" => "UZ", "alpha3" => "UZB", "codigo" => "860"],
                ["nombre" => "Vanuatu", "alpha2" => "VU", "alpha3" => "VUT", "codigo" => "548"],
                ["nombre" => "Santa Sede (la)", "alpha2" => "VA", "alpha3" => "VAT", "codigo" => "336"],
                ["nombre" => "Venezuela (República Bolivariana de)", "alpha2" => "VE", "alpha3" => "VEN", "codigo" => "862"],
                ["nombre" => "Viet Nam", "alpha2" => "VN", "alpha3" => "VNM", "codigo" => "704"],
                ["nombre" => "Wallis y Futuna", "alpha2" => "WF", "alpha3" => "WLF", "codigo" => "876"],
                ["nombre" => "Yemen", "alpha2" => "YE", "alpha3" => "YEM", "codigo" => "887"],
                ["nombre" => "Djibouti", "alpha2" => "DJ", "alpha3" => "DJI", "codigo" => "262"],
                ["nombre" => "Zambia", "alpha2" => "ZM", "alpha3" => "ZMB", "codigo" => "894"],
                ["nombre" => "Zimbabwe", "alpha2" => "ZW", "alpha3" => "ZWE", "codigo" => "716"],
            ];
            foreach ($paises as $pais) {
                $data = [
                    "pais_nombre" => $pais["nombre"],
                    "pais_alpha2" => $pais["alpha2"],
                    "pais_alpha3" => $pais["alpha3"],
                    "pais_codigo" => $pais["codigo"],
                    "pais_estado" => 1,
                ];
                $db->table('pais')->insert($data);
            }

            $provincias = [
                [ "codigo" => "VI", "cp" => "1", "nombre" => "Álava", "tel" => "945"],
                [ "codigo" => "AB", "cp" => "2", "nombre" => "Albacete", "tel" => "967"],
                [ "codigo" => "A", "cp" => "3", "nombre" => "Alacant", "tel" => "950"],
                [ "codigo" => "AL", "cp" => "4", "nombre" => "Almería", "tel" => "920"],
                [ "codigo" => "AV", "cp" => "5", "nombre" => "Ávila", "tel" => "924"],
                [ "codigo" => "BA", "cp" => "6", "nombre" => "Badajoz", "tel" => "924"],
                [ "codigo" => "PM", "cp" => "7", "nombre" => "Illes Balears", "tel" => "971"],
                [ "codigo" => "B", "cp" => "8", "nombre" => "Barcelona", "tel" => "93"],
                [ "codigo" => "BU", "cp" => "9", "nombre" => "Burgos", "tel" => "947"],
                [ "codigo" => "CC", "cp" => "10", "nombre" => "Cáceres", "tel" => "927"],
                [ "codigo" => "CA", "cp" => "11", "nombre" => "Cádiz", "tel" => "956"],
                [ "codigo" => "CS", "cp" => "12", "nombre" => "Castelló", "tel" => "964"],
                [ "codigo" => "CR", "cp" => "13", "nombre" => "Ciudad Real", "tel" => "926"],
                [ "codigo" => "CO", "cp" => "14", "nombre" => "Córdoba", "tel" => "957"],
                [ "codigo" => "C", "cp" => "15", "nombre" => "A Coruña", "tel" => "981"],
                [ "codigo" => "CU", "cp" => "16", "nombre" => "Cuenca", "tel" => "969"],
                [ "codigo" => "GI", "cp" => "17", "nombre" => "Girona", "tel" => "972"],
                [ "codigo" => "GR", "cp" => "18", "nombre" => "Granada", "tel" => "958"],
                [ "codigo" => "GU", "cp" => "19", "nombre" => "Guadalajara", "tel" => "949"],
                [ "codigo" => "SS", "cp" => "20", "nombre" => "Gipuzkoa", "tel" => "943"],
                [ "codigo" => "H", "cp" => "21", "nombre" => "Huelva", "tel" => "959"],
                [ "codigo" => "HU", "cp" => "22", "nombre" => "Huesca", "tel" => "974"],
                [ "codigo" => "J", "cp" => "23", "nombre" => "Jaén", "tel" => "953"],
                [ "codigo" => "LE", "cp" => "24", "nombre" => "León", "tel" => "987"],
                [ "codigo" => "L", "cp" => "25", "nombre" => "Lleida", "tel" => "973"],
                [ "codigo" => "LO", "cp" => "26", "nombre" => "La Rioja", "tel" => "941"],
                [ "codigo" => "LU", "cp" => "27", "nombre" => "Lugo", "tel" => "982"],
                [ "codigo" => "M", "cp" => "28", "nombre" => "Madrid", "tel" => "91"],
                [ "codigo" => "MA", "cp" => "29", "nombre" => "Málaga", "tel" => "95"],
                [ "codigo" => "MU", "cp" => "30", "nombre" => "Murcia", "tel" => "968"],
                [ "codigo" => "NA", "cp" => "31", "nombre" => "Nafarroa", "tel" => "948"],
                [ "codigo" => "OR", "cp" => "32", "nombre" => "Ourense", "tel" => "988"],
                [ "codigo" => "O", "cp" => "33", "nombre" => "Asturias", "tel" => "98"],
                [ "codigo" => "P", "cp" => "34", "nombre" => "Palencia", "tel" => "979"],
                [ "codigo" => "GC", "cp" => "35", "nombre" => "Las Palmas", "tel" => "928"],
                [ "codigo" => "PO", "cp" => "36", "nombre" => "Pontevedra", "tel" => "986"],
                [ "codigo" => "SA", "cp" => "37", "nombre" => "Salamanca", "tel" => "923"],
                [ "codigo" => "TF", "cp" => "38", "nombre" => "Sta. Cruz de Tenerife", "tel" => "922"],
                [ "codigo" => "S", "cp" => "39", "nombre" => "Cantabria", "tel" => "942"],
                [ "codigo" => "SG", "cp" => "40", "nombre" => "Segovia", "tel" => "921"],
                [ "codigo" => "SE", "cp" => "41", "nombre" => "Sevilla", "tel" => "95"],
                [ "codigo" => "SO", "cp" => "42", "nombre" => "Soria", "tel" => "975"],
                [ "codigo" => "T", "cp" => "43", "nombre" => "Tarragona", "tel" => "977"],
                [ "codigo" => "TE", "cp" => "44", "nombre" => "Teruel", "tel" => "978"],
                [ "codigo" => "TO", "cp" => "45", "nombre" => "Toledo", "tel" => "925"],
                [ "codigo" => "V", "cp" => "46", "nombre" => "Valéncia", "tel" => "96"],
                [ "codigo" => "VA", "cp" => "47", "nombre" => "Valladolid", "tel" => "983"],
                [ "codigo" => "BI", "cp" => "48", "nombre" => "Bizkaia", "tel" => "94"],
                [ "codigo" => "ZA", "cp" => "49", "nombre" => "Zamora", "tel" => "980"],
                [ "codigo" => "Z", "cp" => "50", "nombre" => "Zaragoza", "tel" => "976"],
                [ "codigo" => "CE", "cp" => "51", "nombre" => "Ceuta", "tel" => "956"],
                [ "codigo" => "ML", "cp" => "52", "nombre" => "Melilla", "tel" => "95"],
            ];

            foreach ($provincias as $provincia) {
                $data = [
                    "provincia_nombre" => $provincia["nombre"],
                    "provincia_codigo" => $provincia["codigo"],
                    "provincia_cp" => $provincia["cp"],
                    "provincia_tel" => $provincia["tel"],
                    "provincia_pais_id" => 64,
                    "provincia_estado" => 1,
                ];
                $db->table('provincia')->insert($data);
            }
        }
}
